/**
 * * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
    docs: [
        {
            type: 'doc',
            id: 'welcome',
        },
        {
            type: 'doc',
            id: 'overview',
        }, {
            type: "category",
            label: 'Getting Started',

            link: {
                type: "doc",
                id:'getting_started/getting_started'

            },
            items: [
                {
                    type: "doc",
                    id: "getting_started/rust",
                    label: 'Rust'
                },
                {
                    type: "doc",
                    id: "getting_started/nodejs",
                    label: 'Node.js'
                },
                {
                    type: "doc",
                    id: "getting_started/java",
                    label: 'Java'
                },
                {
                    type: "doc",
                    id: "getting_started/python",
                    label: 'Python'
                },
            ]
        },
        {
            type: "category",
            label: "How To",
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'how_tos'
                },

            ],

        },
        {
            type: "category",
            label: "API Reference",
            items: [
                {
                    type: "doc",
                    id: "libraries/rust/api_reference",
                    label: "Rust",
                },
                {
                    type: 'category',
                    label: 'Node.js',
                    items: [
                        {
                            type: "doc",
                            id: "libraries/nodejs/references/api_ref",
                            label: 'API Reference'
                        },
                        {
                            type: "category",
                            label: "Classes",
                            items: [
                                {
                                    type: 'autogenerated',
                                    dirName: 'libraries/nodejs/references/classes'
                                },
                            ]
                        },
                        {
                            type: "category",
                            label: "Enums",
                            items: [
                                {
                                    type: 'autogenerated',
                                    dirName: 'libraries/nodejs/references/enums'
                                },
                            ]
                        },
                        {
                            type: "category",
                            label: "Interfaces",
                            items: [
                                {
                                    type: 'autogenerated',
                                    dirName: 'libraries/nodejs/references/interfaces'
                                },
                            ]
                        },
                    ]
                },
                {
                    type: "doc",
                    id: "libraries/java/api_reference",
                    label: "Java",
                },
                {
                    type: "category",
                    label: "Python",
                    items:[
                        {
                            type:"autogenerated",
                            dirName:'libraries/python/references/iota_client'
                        }
                    ],
                },
            ],
        },
        {
            type: 'doc',
            id: 'troubleshooting',
            label: 'Troubleshooting'
        },
        {
            type: 'doc',
            id: 'contribute',
            label: 'Contribute',
        }
    ]
};
