use bee_bundle::Transaction;
use iota_conversion::{trytes, Trinary};

pub(crate) fn tx_trytes(tx: &Transaction) -> String {
    trytes(tx.payload().as_bytes()).unwrap()
        + &trytes(tx.address().as_bytes()).unwrap()
        + &tx.value().0.trits_with_length(81).trytes().unwrap()
        + &trytes(tx.obsolete_tag().as_bytes()).unwrap()
        + &(tx.timestamp().0 as i64)
            .trits_with_length(27)
            .trytes()
            .unwrap()
        + &(tx.index().0 as i64)
            .trits_with_length(27)
            .trytes()
            .unwrap()
        + &(tx.last_index().0 as i64)
            .trits_with_length(27)
            .trytes()
            .unwrap()
        + &trytes(tx.bundle().as_bytes()).unwrap()
        + &trytes(tx.trunk().as_bytes()).unwrap()
        + &trytes(tx.branch().as_bytes()).unwrap()
        + &trytes(tx.tag().as_bytes()).unwrap()
        + &(tx.attachment_ts().0 as i64)
            .trits_with_length(27)
            .trytes()
            .unwrap()
        + &(tx.attachment_lbts().0 as i64)
            .trits_with_length(27)
            .trytes()
            .unwrap()
        + &(tx.attachment_ubts().0 as i64)
            .trits_with_length(27)
            .trytes()
            .unwrap()
        + &trytes(tx.nonce().as_bytes()).unwrap()
}
